post:
  summary: Create a Nomad job deployment
  x-internal: true
  x-catalogRelations:
    - type: ownedBy
      key: borsch
  tags:
    - NomadJobs
  security:
    - InternalAuth: []
  operationId: createNomadJobDeployment
  description: Triggers a new deployment for the specified Nomad job.
  parameters:
    - name: jobId
      in: path
      required: true
      example: project-my-project
      schema:
        type: string
        description: Nomad job ID (e.g. project-my-project).
  responses:
    '204':
      description: Deployment triggered successfully.
    '400':
      $ref: ../../common/responses/BadRequestError.yaml
    '401':
      $ref: ../../common/responses/UnauthorizedError.yaml
    '403':
      $ref: ../../common/responses/ForbiddenError.yaml
    '404':
      $ref: ../../common/responses/NotFoundError.yaml
    '500':
      $ref: ../../common/responses/InternalServerError.yaml
