get:
  tags:
    - Projects
  security:
    - UserCookie: []
  summary: Retrieve a project
  x-internal: true
  x-catalogRelations:
    - type: ownedBy
      key: to-the-moon
  operationId: getProjectById
  parameters:
    - $ref: ../../components/parameters/path/OrgId.yaml
    - $ref: ../../components/parameters/path/ProjectId.yaml
  responses:
    '200':
      description: OK.
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/project/Project.yaml
    '401':
      $ref: ../../common/responses/UnauthorizedError.yaml
    '403':
      $ref: ../../common/responses/ForbiddenError.yaml
    '404':
      $ref: ../../common/responses/NotFoundError.yaml
    '500':
      $ref: ../../common/responses/InternalServerError.yaml
put:
  tags:
    - Projects
  security:
    - UserCookie: []
  summary: Replace a project
  x-internal: true
  x-catalogRelations:
    - type: ownedBy
      key: to-the-moon
  operationId: updateProject
  parameters:
    - $ref: ../../components/parameters/path/OrgId.yaml
    - $ref: ../../components/parameters/path/ProjectId.yaml
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/project/Project.yaml
  responses:
    '200':
      description: OK.
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/project/Project.yaml
    '400':
      $ref: ../../common/responses/BadRequestError.yaml
    '401':
      $ref: ../../common/responses/UnauthorizedError.yaml
    '403':
      $ref: ../../common/responses/ForbiddenError.yaml
    '404':
      $ref: ../../common/responses/NotFoundError.yaml
    '500':
      $ref: ../../common/responses/InternalServerError.yaml
patch:
  tags:
    - Projects
  security:
    - UserCookie: []
  summary: Partially update a project
  x-internal: true
  x-catalogRelations:
    - type: ownedBy
      key: to-the-moon
  operationId: patchProject
  parameters:
    - $ref: ../../components/parameters/path/OrgId.yaml
    - $ref: ../../components/parameters/path/ProjectId.yaml
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/project/PatchProjectRequest.yaml
  responses:
    '200':
      description: OK.
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/project/Project.yaml
    '400':
      $ref: ../../common/responses/BadRequestError.yaml
    '401':
      $ref: ../../common/responses/UnauthorizedError.yaml
    '403':
      $ref: ../../common/responses/ForbiddenError.yaml
    '404':
      $ref: ../../common/responses/NotFoundError.yaml
    '500':
      $ref: ../../common/responses/InternalServerError.yaml
delete:
  tags:
    - Projects
  security:
    - UserCookie: []
  summary: Delete a project
  x-internal: true
  x-catalogRelations:
    - type: ownedBy
      key: to-the-moon
  operationId: deleteProject
  parameters:
    - $ref: ../../components/parameters/path/OrgId.yaml
    - $ref: ../../components/parameters/path/ProjectId.yaml
  responses:
    '204':
      $ref: ../../common/responses/NoContent.yaml
    '401':
      $ref: ../../common/responses/UnauthorizedError.yaml
    '403':
      $ref: ../../common/responses/ForbiddenError.yaml
    '404':
      $ref: ../../common/responses/NotFoundError.yaml
    '500':
      $ref: ../../common/responses/InternalServerError.yaml
