type: object
properties:
  object:
    type: string
    enum: [productAnalyticsFeaturesConfig]
  featureContent:
    type: object
    description: Feature configuration value used by a project from the latest build.
    additionalProperties: true
    readOnly: true
  featureRawContent:
    type: object
    description: Raw feature configuration value used by a project from the latest build.
    additionalProperties: true
  featureFirstRawContent:
    type: object
    description: Raw feature configuration value used by a project from the first build.
    additionalProperties: true
    readOnly: true
required:
  - object
  - featureContent
  - featureRawContent
  - featureFirstRawContent