put:
  tags:
    - Respect Monitoring
  security:
    - UserCookie: []
  summary: Replace a notifications SLA configuration
  x-internal: true
  x-catalogRelations:
    - type: ownedBy
      key: to-the-moon
  operationId: updateNotificationsSlaConfig
  parameters:
    - $ref: ../../components/parameters/path/OrgId.yaml
    - $ref: ../../components/parameters/path/ProjectId.yaml
    - $ref: ../../components/parameters/path/ApiMonitoringNotificationsSlaConfigId.yaml
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/api-monitoring/ApiMonitoringNotificationsSlaConfig.yaml
  responses:
    '200':
      description: Respect Monitoring notifications sla config updated.
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/api-monitoring/ApiMonitoringNotificationsSlaConfig.yaml
    '400':
      $ref: ../../common/responses/BadRequestError.yaml
    '401':
      $ref: ../../common/responses/UnauthorizedError.yaml
    '403':
      $ref: ../../common/responses/ForbiddenError.yaml
    '404':
      $ref: ../../common/responses/NotFoundError.yaml
    '500':
      $ref: ../../common/responses/InternalServerError.yaml
