description: GitLab Project details.
type: object
required:
  - id
  - name
  - description
  - web_url
  - avatar_url
  - git_ssh_url
  - git_http_url
  - namespace
  - visibility_level
  - path_with_namespace
  - default_branch
  - homepage
  - url
  - ssh_url
  - http_url
properties:
  id:
    type: integer
    description: Unique identifier of the project.
  name:
    type: string
    description: The name of the project.
  description:
    type: string
    description: The description of the project.
  web_url:
    type: string
    description: The URL to view the repository.
    format: uri
    example: http://example.com/gitlabhq/gitlab-test
  avatar_url:
    type: string
    description: Repository avatar url.
    format: uri
    example: https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40&d=identicon
  git_ssh_url:
    type: string
    description: SSH url of a project.
    format: uri
    example: ssh://git@example.com/gitlabhq/gitlab-test.git
  git_http_url:
    type: string
    description: Url of a project.
    format: uri
    example: http://example.com/gitlabhq/gitlab-test.git
  namespace:
    type: string
    description: Project namespace.
    example: GitlabHQ
  visibility_level:
    type: integer
    description: Visibility level of a project.
    example: 20
  path_with_namespace:
    type: string
    description: Project path including namespace.
    example: gitlabhq/gitlab-test
  default_branch:
    type: string
    description: Project default branch.
    example: develop
  homepage:
    type: string
    description: Project homepage url.
    format: uri
    example: http://example.com/gitlabhq/gitlab-test
  url:
    type: string
    description: Url of a project.
    format: uri
    example: http://example.com/gitlabhq/gitlab-test.git
  ssh_url:
    type: string
    description: SSH url of a project.
    format: uri
    example: ssh://git@example.com/gitlabhq/gitlab-test.git
  http_url:
    type: string
    description: Url of a project.
    format: uri
    example: http://example.com/gitlabhq/gitlab-test.git
additionalProperties: false
title: Project
