type: object
properties:
  id:
    description: Respect Monitoring notifications Slack config ID. Unique identifier prefixed with `amnac_`.
    type: string
    pattern: ^amnac_[0-9abcdefghjkmnpqrstvwxyz]{26}$
    example: amnac_01h2zvgfdqex5na189kdg39d6s
    readOnly: true
  object:
    description: Entity name.
    type: string
    enum: [respectMonitoringNotificationsSlackConfig]
    example: respectMonitoringNotificationsSlackConfig
    readOnly: true
  uri:
    description: URI reference to this Respect Monitoring notifications Slack config.
    type: string
    format: uri
    readOnly: true
    example: https://app.cloud.redocly.com/api/orgs/org_01hh1t9sa6gwfv5naz04gr7ehm/projects/prj_01hh1t9sa6gwfv5naz04gr7ehm/respect-monitoring-notifications-slack-configs/amnac_01h2zvgfdqex5na189kdg39d6s
  slackAppInstallationId:
    description: Slack app installation ID. Unique identifier prefixed with `amnai_`.
    type: [string, 'null']
    pattern: ^amnai_[0-9abcdefghjkmnpqrstvwxyz]{26}$
    example: amnai_01hh1t9sa6gwfv5naz04gr7ehm
  slackChannelId:
    description: Slack channel ID.
    type: [string, 'null']
    example: C012AB3CD
  workflowId:
    description: Respect Monitoring workflow ID.
    type: string
    example: amw_01h2zvgfdqex5na189kdg39d6s
  notifyAboutRecovery:
    description: Determine if notification about first successful run after failed runs should be sent.
    type: boolean
    example: false
  repeatNotificationAfter:
    description: Specify how many errors to wait before re-sending notification.
    type: number
    example: 5
  initialErrorThreshold:
    description: Specify how many errors to wait before sending first error notification.
    type: number
    example: 3
  severity:
    description: Severity levels on which email notifications should be sent.
    type: array
    items:
      type: string
      enum: [ERROR, WARNING, SUCCESS]
    uniqueItems: true
    example:
      - ERROR
  createdAt:
    description: Created date.
    type: string
    format: date-time
    example: '2023-06-15T15:41:42.696Z'
    readOnly: true
required:
  - id
  - object
  - uri
  - workflowId
  - notifyAboutRecovery
  - repeatNotificationAfter
  - initialErrorThreshold
  - severity
  - createdAt
