type: object
properties:
  object:
    description: Entity name.
    type: string
    enum: [respectMonitoringNotificationsSlaConfigList]
    example: respectMonitoringNotificationsSlaConfigList
    readOnly: true
  data:
    description: List of Respect Monitoring notifications sla configs.
    type: array
    items:
      $ref: ApiMonitoringNotificationsSlaConfig.yaml
  page:
    $ref: ../Page.yaml
required:
  - object
  - page
  - data
