type: object
properties:
  id:
    description: Respect Monitoring notifications email config ID. Unique identifier prefixed with `amnaco_`.
    type: string
    pattern: ^amneco_[0-9abcdefghjkmnpqrstvwxyz]{26}$
    example: amneco_01h2zvgfdqex5na189kdg39d6s
    readOnly: true
  object:
    description: Entity name.
    type: string
    enum: [respectMonitoringNotificationsEmailConfig]
    example: respectMonitoringNotificationsEmailConfig
    readOnly: true
  userId:
    description: User ID. Unique identifier prefixed with `usr_`.
    type: string
    pattern: ^usr_[0-9abcdefghjkmnpqrstvwxyz]{26}$
    example: usr_01hh1t9sa6gwfv5naz04gr7ehm
  workflowId:
    description: Respect Monitoring workflow ID.
    type: string
    example: amw_01h2zvgfdqex5na189kdg39d6s
  notifyAboutRecovery:
    description: Determine if notification about first successful run after failed runs should be sent.
    type: boolean
    example: false
  repeatNotificationAfter:
    description: Specify how many errors to wait before re-sending notification.
    type: number
    example: 5
  initialErrorThreshold:
    description: Specify how many errors to wait before sending first error notification.
    type: number
    example: 3
  severity:
    description: Severity levels on which email notifications should be sent.
    type: array
    items:
      type: string
      enum: [ERROR, WARNING, SUCCESS]
    uniqueItems: true
    example:
      - ERROR
  createdAt:
    description: Created date.
    type: string
    format: date-time
    example: '2023-06-15T15:41:42.696Z'
    readOnly: true
  uri:
    type: string
    format: uri
    description: Canonical URI for the notifications email config resource.
    readOnly: true
    example: https://app.cloud.redocly.com/api/orgs/org_01hh1t9sa6gwfv5naz04gr7ehm/projects/prj_01hh1t9sa6gwfv5naz04gr7ehm/respect-monitoring-notifications-email-configs/amneco_01h2zvgfdqex5na189kdg39d6s
required:
  - id
  - object
  - userId
  - workflowId
  - notifyAboutRecovery
  - repeatNotificationAfter
  - initialErrorThreshold
  - severity
  - createdAt
  - uri