openapi: 3.1.0
info:
  title: Redocly Cafe
  version: 1.0.0
  contact:
    email: team@redocly.com
    url: https://redocly.com/contact-us/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://redocly.com/subscription-agreement
servers:
  - url: https://cafe.cloud.redocly.com
    description: Live server.
tags:
  - name: Products
    description: Operations related to products.
paths:
  # @chunk {"steps": ["openapi-list-menu-items", "arazzo-step-operation"]}
  /menu:
    get:
      tags:
        - Products
      summary: List all menu items
      operationId: listMenuItems
      security: []
      parameters:
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemList'
        '400':
          description: Bad request - invalid input parameters.
        '500':
          description: Internal server error.
  # @chunk-end
components:
  parameters:
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
      example: 10
  schemas:
    Page:
      type: object
      properties:
        endCursor:
          type:
            - string
            - 'null'
        startCursor:
          type:
            - string
            - 'null'
        hasNextPage:
          type: boolean
        hasPrevPage:
          type: boolean
        limit:
          type: integer
          minimum: 1
          maximum: 100
          default: 10
        total:
          type: integer
          minimum: 0
      required:
        - endCursor
        - startCursor
        - hasNextPage
        - hasPrevPage
        - limit
        - total
    MenuBaseItem:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        id:
          type: string
          readOnly: true
          pattern: ^prd_[0-9abcdefghjkmnpqrstvwxyz]{26}$
        object:
          type: string
          const: menuItem
          readOnly: true
        name:
          type: string
          minLength: 1
          maxLength: 50
        price:
          type: integer
          minimum: 0
        photo:
          writeOnly: true
          type:
            - string
            - 'null'
          format: binary
        photoUrl:
          readOnly: true
          type: string
          format: uri
        photoTextDescription:
          type:
            - string
            - 'null'
      required:
        - id
        - name
        - price
        - createdAt
        - updatedAt
        - object
    Beverage:
      allOf:
        - type: object
          properties:
            category:
              type: string
              const: beverage
            volume:
              type: number
              exclusiveMinimum: 0
            containsCaffeine:
              type: boolean
        - $ref: '#/components/schemas/MenuBaseItem'
    Dessert:
      allOf:
        - type: object
          properties:
            category:
              type: string
              const: dessert
            calories:
              type: number
              exclusiveMinimum: 0
        - $ref: '#/components/schemas/MenuBaseItem'
    MenuItem:
      discriminator:
        propertyName: category
        mapping:
          beverage: '#/components/schemas/Beverage'
          dessert: '#/components/schemas/Dessert'
      oneOf:
        - $ref: '#/components/schemas/Beverage'
        - $ref: '#/components/schemas/Dessert'
      required:
        - category
    # @chunk {"steps": ["openapi-broken-schema", "schema-failure", "schema-fix"]}
    MenuItemList:
      type: array
      items:
        type: object
        properties:
          object:
            type: string
            const: list
          page:
            $ref: '#/components/schemas/Page'
          items:
            type: array
            items:
              $ref: '#/components/schemas/MenuItem'
        required:
          - object
          - page
          - items
    # @chunk-end
    Error:
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          default: about:blank
        title:
          type: string
        status:
          type: integer
          format: int32
          minimum: 100
          exclusiveMaximum: 600
        instance:
          type: string
          format: uri-reference
        details:
          type: object
          additionalProperties: true
      required:
        - type
        - title
        - status
