type: ['null', object]
description: Notification settings.
properties:
  id:
    type: ['string', 'null']
    description: Unique identifier of the notification settings.
    readOnly: true
    example: notset_01abc123
  object:
    type: string
    description: Entity name.
    const: notificationSettings
    readOnly: true
    example: notificationSettings
  uri:
    type: string
    format: uri
    description: URI of the notification settings resource.
    readOnly: true
    example: urn:redocly:notificationSettings
  ignoredEvents:
    description: Ignore notifications about events from the list.
    type: array
    items:
      $ref: ./NotificationEvent.yaml
  isMentioned:
    description: Triggers notification when the user is mentioned.
    type: boolean
    example: true
  isContributor:
    description: Triggers notification when commit to a branch with a PR opened.
    type: boolean
    example: true
  isReviewer:
    description: Triggers notification when user is an assigned reviewer.
    type: boolean
    example: true
required:
  - id
  - object
  - uri
