get:
  summary: Wake up project
  x-internal: true
  x-catalogRelations:
    - type: ownedBy
      key: borsch
  tags:
    - Project deploys
  security: []
  operationId: wakeUps
  parameters:
    - in: query
      name: search
      schema:
        type: string
      required: true
      description: ID or Host of the project deploy to wake up.
      example: acme.com
  responses:
    '302':
      description: Redirect to loading screen.
      headers:
        Location:
          description: Users are directed to a prolonged loading screen on the health page until the project deployment is reset.
          schema:
            type: string
          example: https://project.com/health/
    '400':
      $ref: ../../common/responses/BadRequestError.yaml
    '404':
      $ref: ../../common/responses/NotFoundError.yaml
    '500':
      $ref: ../../common/responses/InternalServerError.yaml
    
